---
- name: Install dev utils
  include_role:
    name: utils
    tasks_from: "{{ item }}"
  loop:
    - intellij

- name: Install dev tools
  include_role:
    name: tools
    tasks_from: "{{ item }}"
  loop:
    - git
    - graphviz
    - pyenv
    - shell_check
    - yamllint

- name: Install docker
  include_role:
    name: docker
