---
- hosts: localhost
  sudo: no
  connection: local

  tasks:
    # this seriously annoys me. I don't want anything opening when I plug in
    # my phone or a camera.
    - name: Disable ImageCapture hotplug.
      command: >
        defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool YES

    - name: Update Homebrew and install cask
      homebrew: update_homebrew=yes upgrade_all=no
      homebrew: name=brew-cask state=present

    - name: Install AWS tools.
      homebrew: name={{ item }} state=present
      with_items:
        - awscli
        - amazon-ecs-cli

    - name: Install pyenv and friends.
      homebrew: name={{ item }} state=present
      with_items:
        - matplotlib
        - pyenv
        - pyenv-pip-migrate
        - pyenv-virtualenv
    - include: python.yml

    - name: Install network tools.
      homebrew: name={{ item }} state=present
      with_items:
        - blucat
        - curl
        - dnscrypt-proxy
        - dnsmasq
        - ettercap
        - httping
        - kafkacat
        - mtr
        - nmap
        - openvpn
        - speedtest_cli
        - sshuttle
        - tor
        - torsocks
        - tuntap

    - name: install dev tools.
      homebrew: name={{ item }} state=present
      with_items:
        - docker
        - docker-machine
        - git
        - git-subrepo
        - go
        - saltstack
        - scala
        - sqlite
        - tmux

    - name: random other crap.
      homebrew: name={{ item }} state=present
      with_items:
        - ffmpeg
        - irssi
        - silc-client
        - youtube-dl

    - name: Things from Cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - bittorrent-sync
        - google-chrome
        - evernote
        - iterm2
        - osxfuse
        - skype
        - transmission
        - wireshark
        - virtualbox
        - virtualbox-extension-pack
        - vagrant
        - xquartz
