---
- hosts: localhost
  connection: local

  vars:
    # brew settings for macos
    brew_install: yes
    brew_root: /usr/local

  pre_tasks:
    - name: Create System groups
      group_by: key="sys_{{ ansible_facts['system'] | lower }}"

    - name: Create Hardware groups
      group_by: key="hw_{{ ansible_model | lower | regex_search('([a-z]+)') }}"

- hosts: sys_darwin
  gather_facts: false
  vars:
    brew_root: /usr/local

  roles:
    - macos
    - common

- hosts: hw_macbookpro
  gather_facts: false

  roles:
    - laptop

- hosts: hw_macmini
  gather_facts: false

  roles:
    - desktop