---
- hosts: localhost
  connection: local

  vars:
    # brew settings for macos
    brew_install: yes
    brew_root: /usr/local

  pre_tasks:
    - name: Laptop?
      shell: echo "yes"
      register: macbook
      when:
        - (ansible_model.find('MacBook') != -1 and ansible_distribution == "MacOSX")

  roles:
    - macos
    - home
    # - python  // disabled for now due to significant revamp in how pyenv is leveraged.

