---
- hosts: all

  tasks:
  # OSX defaults fixes first
  - name: Disable HotPlug for ImageCapture
    osx_defaults:
      domain: com.apple.ImageCapture
      key: disableHotPlug
      type: bool
      value: true
      state: present

  - name: Enable Screensaver password requests
    osx_defaults:
      domain: com.apple.screensaver
      key: askForPassWord
      type: int
      value: 1
      state: present

  - name: Require password immediately
    osx_defaults:
      domain: com.apple.screensaver
      key: askForPassWordDelay
      type: int
      value: 0
      state: present

  - name: Set "nohidden" on ~/Library
    command: chflags nohidden ~/Library


  # setup homebrew/taps
  - name: install Homebrew taps
    homebrew_tap: tap={{ item }} state=present
    with_items:
      - caskroom/cask
      - homebrew/completions
      - homebrew/games
      - homebrew/python

  - name: Update Homebrew
    homebrew: update_homebrew=yes upgrade_all=no

  - name: Things from Cask
    homebrew_cask: name={{ item }} state=installed
    with_items:
      - caffeine
      - crashplan
      - docker
      - google-chrome
      - evernote
      - ios-console
      - istumbler
      - iterm2
      - keepassx
      - kitematic
      - osxfuse
      - mactex
      - postman
      - soundflower
      - slack
      - skype
      - sonos
      - sshfs
      - transmission
      - tuntap
      - tunnelblick
      - wireshark
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
      - vlc
      - xquartz

  - name: Install AWS tools.
    homebrew: name={{ item }} state=latest
    with_items:
      - awscli
      - amazon-ecs-cli

  - name: Install pyenv and friends.
    homebrew: name={{ item }} state=latest
    with_items:
      - matplotlib
      - pyenv
      - pyenv-pip-migrate
      - pyenv-virtualenv

  - name: Install network and privacy tools.
    homebrew: name={{ item }} state=latest
    with_items:
      - curl
      - dnscrypt-proxy
      - dnsmasq
      - ettercap
      - httping
      - kafkacat
      - mtr
      - nmap
      - openvpn
      - speedtest_cli
      - sshuttle
      - tor
      - torsocks

  - name: Install Dev/Ops tools.
    homebrew: name={{ item }} state=latest
    with_items:
      # - docker :: moved to cask
      - docker-machine
      - dockviz
      - git
      - git-subrepo
      - go
      - saltstack
      - sqlite
      - tmux

  - name: Install Bash completions.
    homebrew: name={{ item }} state=latest
    with_items:
      - brew-cask-completion
      - docker-completion
      - docker-compose-completion
      - docker-machine-completion
      - pip-completion
      - vagrant-completion

  - name: random other crap.
    homebrew: name={{ item }} state=latest
    with_items:
      - mas
      - geoip
      - geoipupdate
      - ffmpeg
      - irssi
      - silc-client
      - youtube-dl
