---
- hosts: localhost
  connection: local

  vars:
    # brew settings for macos
    brew_install: yes
    brew_root: /usr/local

  pre_tasks:
    - name: Create System groups
      group_by: key="sys_{{ ansible_facts['system'] | lower }}"

    - name: Create Hardware groups
      group_by: key="hw_{{ ansible_model | lower | regex_search('([a-z]+)') }}"

    - debug:
        msg: "function: {{ function }}"

    # add in via --extra-vars 'function="[\"foo\", \"bar\"]"'. Defined roles can then be added below
    # current "functional" host_groups are "work" and "vpn". If not defined, it does nothing.
    - name: Group by function
      group_by: key="{{ item }}"
      loop: "{{ function }}"
      when: function is defined

    - debug:
        msg: "GROUPS: {{ groups }}"

- hosts: sys_darwin
  gather_facts: false
  vars:
    brew_root: /usr/local

  roles:
    - macos
    - common

- hosts: hw_macbookpro
  gather_facts: false

  roles:
    - laptop

- hosts: hw_macmini
  gather_facts: false

  roles:
    - desktop
    - remotes

- hosts: work
  gather_facts: false

  roles:
    - devel
    - vm

- hosts: ops
  gather_facts: false

  roles:
    - devel
    - operations
    - network

- hosts: secops
  gather_facts: false

  roles:
    - devel
#    - secops

- hosts: netadmin
  gather_facts: false

  vars:
    netadmin_address: "{{ netadmin.network.ethernet.address }}"
    netadmin_netmask: "{{ netadmin.network.ethernet.netmask }}"
    netadmin_gateway: "{{ netadmin.network.ethernet.gateway }}"
    vlan0_parent: Ethernet
    vlan0_name: "{{ netadmin.network.vlan0.name }}"
    vlan0_tag: "{{ netadmin.network.vlan0.tag }}"

  roles:
    - netadmin