---
- hosts: localhost
  connection: local

  vars:
    # brew settings for macos
    brew_install: yes
    brew_root: /usr/local
    debug: True

  pre_tasks:
    - name: Create Architecture Groups
      group_by: key="arch_{{ ansible_architecture | lower }}"

    - name: Create System groups
      group_by: key="sys_{{ ansible_facts['system'] | lower }}"

    - name: Create Hardware groups
      group_by: key="hw_{{ ansible_model | lower | regex_search('([a-z]+)') }}"

    - name: Group by function
      group_by: key="{{ item }}"
      loop: "{{ func }}"
      when: func is defined

    - debug:
        msg: "GROUPS: {{ groups }}"
      when: debug == True

- name: Arch Intel 64
  hosts: arch_x86_64
  gather_facts: false

- name: Darwin Specific
  hosts: sys_darwin
  gather_facts: false

  roles:
    - base

- name: MacBook Pro
  hosts: hw_macbookpro
  gather_facts: false

- name: Mac Mini
  hosts: hw_macmini
  gather_facts: false

- name: Work
  hosts: work
  gather_facts: false

  roles:
    - cloud
    - developer

- name: Personal
  hosts: personal
  gather_facts: false

  roles:
    - cloud
    - developer