---
- name: Install DisplayLink
  community.general.homebrew_cask:
    name: displaylink
    state: present
  register: displaylink_installed
  when: arch == "x86_64" and system == "darwin" and displaylink_installed is undefined

- name: Set start on boot
  community.general.osx_defaults:
    domain: com.displaylink.DisplayLinkUserAgent
    key: AppAutostart
    type: bool
    value: "{{ displaylink_autostart | defaults("false") }}"
    state: present
  when: displaylink_installed.failed != True and displaylink_installed is defined

- debug:
    msg: "{{ displaylink_installed }}"
  when: debug == True and displaylink_installed is defined
