---
- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: present
  register: tmux_installed
  when: tmux_installed is undefined

- name: Install xpanes
  community.general.homebrew:
    name: tmux-xpanes
    state: present
  register: xpanes_installed
  when: tmux_installed.failed != True and xpanes_installed is undefined

- debug:
    msg: "{{ tmux_installed }}"
  when: debug == True and tmux_installed is defined

- debug:
    msg: "{{ xpanes_installed }}"
  when: debug == True and xpanes_installed is defined