---
# Python with support for pyenv. Specific pips, etc installed.
# adapted from https://supportex.net/blog/2014/10/ansible-installing-pyenv-centos/

- name: Is pyenv installed
  shell: "test -x $(which pyenv) && echo 'yes'"
  environment:
    PATH: "/usr/local/bin:{{ ansible_user_dir }}/.pyenv/bin:{{ ansible_env.PATH }}"
  register: pyenv

- debug:
    var: pyenv
  when: debug

- name: Is pyenv-virtualenv installed
  shell: "{{ ansible_user_dir }}/.pyenv/bin/pyenv commands | grep virtualenv"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: pyenv_virtualenv
  when: pyenv.stdout == 'yes'

- name: Install pyenv via git.
  git:
    repo: 'git://github.com/yyuu/pyenv.git'
    dest: "{{ ansible_user_dir }}/.pyenv/ }}"
  when: pyenv.stdout != 'yes'
  register: pyenv

- name: Text block for .bashrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  when: pyenv.stdout == 'yes'

#- name: install specific versions for pyenv
#  shell: pyenv install 2.7.13'
#  when: pyenv_present
#
#- name: Activate python 2.7.13
#  shell: pyenv global 2.7.13'
#  when: pyenv_present
#
#- name: Install python modules to pyenv...
#  pip: name={{ item }}
#  when: pyenv is present
#  with_items:
#   - boto
#   - boto3
#   - botocore
