---
# Python with support for pyenv. Specific pips, etc installed.
# adapted from https://supportex.net/blog/2014/10/ansible-installing-pyenv-centos/

- name: Is pyenv installed
  shell: "test -x $(which pyenv) && echo 'yes'"
  register: pyenv_present

- name: Install pyenv via git.
  git:
    repo: 'git://github.com/yyuu/pyenv.git'
    dest: "{{ ansible_env.HOME }}/.pyenv/ }}"
  when: pyenv_present|failed

- name: Set up bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PYENV_ROOT="$HOME/.pyenv"'
    state: present

- name: Set PATH variable
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'PATH=$PYENV_ROOT/bin:$PATH'
    state: present

- name: Get EVAL in place
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(pyenv init -)"'
    state: present

- name: Install pyenv-virtualenv
  git:
    repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"

- name: Set pyenv-virtualenv eval.
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(pyenv virtualenv-init -)"'
    state: present
    insertafter: '^eval "$(pyenv init -)"'

#- name: install specific versions for pyenv
#  shell: pyenv install 2.7.13'
#  when: pyenv_present
#
#- name: Activate python 2.7.13
#  shell: pyenv global 2.7.13'
#  when: pyenv_present
#
#- name: Install python modules to pyenv...
#  pip: name={{ item }}
#  when: pyenv_present
#  with_items:
#   - boto
#   - boto3
#   - botocore
