---
# Python with support for pyenv. Specific pips, etc installed.
# adapted from https://supportex.net/blog/2014/10/ansible-installing-pyenv-centos/

- name: Is pyenv installed
  shell: "test -x $(which pyenv) && echo 'yes'"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: pyenv_present
  ignore_errors: True

- name: Is pyenv-virtualenv installed
  shell: "test -x $(which pyenv-virtualenv) && echo 'yes'"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: pyenv_virtualenv_present
  ignore_errors: True

- name: Install pyenv via git.
  git:
    repo: 'git://github.com/yyuu/pyenv.git'
    dest: "{{ ansible_env.HOME }}/.pyenv/ }}"
  when: pyenv_present

- name: Text block for .profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"

#- name: install specific versions for pyenv
#  shell: pyenv install 2.7.13'
#  when: pyenv_present
#
#- name: Activate python 2.7.13
#  shell: pyenv global 2.7.13'
#  when: pyenv_present
#
#- name: Install python modules to pyenv...
#  pip: name={{ item }}
#  when: pyenv_present
#  with_items:
#   - boto
#   - boto3
#   - botocore
