---
# brew components
#
- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=no

- name: Brew taps.
  homebrew_tap: tap={{ taps }} state=present
  loop:
    - caskroom/cask
    - homebrew/completions
    - homebrew/science
    - homebrew/python
  loop_control:
    loop_var: taps

- name: Install Casks
  homebrew_cask: name={{ casks }} state=installed
  ignore_errors: yes
  loop:
    - caffeine
    - docker
    - google-chrome
    - firefox
    - evernote
    - iterm2
    - kitematic
    - slack
    - transmission
    - xquartz
    - pycharm-ce
  loop_control:
    loop_var: casks

- name: Install MacBook Specific apps
  homebrew_cask: name={{ laptops }} state=installed
  when: ansible_model.find("MacBook") != -1
  loop:
    - istumbler
    - tuntap
    - tunnelblick
  loop_control:
    loop_var: laptops

- name: Install VM stuff
  homebrew_cask: name={{ vms }} state=installed
  loop:
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
    - docker-machine
    - docker-machine-driver-xhyve
  loop_control:
    loop_var: vms

- name: Install Music Stuff
  homebrew_cask: name={{ musics }} state=installed
  loop:
    - sonos
    - spotify
  loop_control:
    loop_var: musics

- name: Install Shell Tools
  homebrew: name={{ shells }} state=latest
  loop:
    - tmux
    - irssi
    - speedtest_cli
    - bash-completion
    - brew-cask-completion
    - docker-completion
    - pip-completion
    - vagrant-completion
  loop_control:
    loop_var: shells

- name: Install compilers
  homebrew: name={{ compilers }} state=latest
  loop:
    - go
  loop_control:
    loop_var: compilers


- name: Install DevOps Tools
  homebrew: name={{ devops }} state=latest
  loop:
    - awscli
    - amazon-ecs-cli
    - packer
    - terraform
    - xhyve
    - dockviz
  loop_control:
    loop_var: devops

- name: Install Security/Privacy Tools
  homebrew: name={{ securitys }} state=latest
  loop:
    - ettercap
    - httping
    - nmap
    - gpg
    - sshuttle
    - tor
    - torsocks
  loop_control:
    loop_var: securitys

