---
# brew components
#

- name: Brew taps.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - homebrew/completions
    - homebrew/science
    - homebrew/python


- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=no

- name: Install Casks
  homebrew_cask: name={{ item }} state=installed
  ignore_errors: yes
  loop:
    - caffeine
    - docker
    - google-chrome
    - firefox
    - evernote
    - iterm2
    - kitematic
    - slack
    - transmission
    - xquartz

- name: Install MacBook Specific Casks
  homebrew_cask: name={{ item }} state=installed
  when: ansible_model.find("MacBook") != -1
  loop:
    - istumbler
    - tuntap
    - tunnelblick

- name: Install VM stuff
  homebrew_cask: name={{ item }} state=installed
  loop:
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
    - docker-machine
    - docker-machine-driver-xhyve

- name: Install Music Stuff
  homebrew_cask: name={{ item }} state=installed
  loop:
    - sonos
    - spotify

- name: Install Shell Tools
  homebrew: name={{ item }} state=latest
  loop:
    - tmux
    - irssi
    - speedtest_cli
    - bash-completion
    - brew-cask-completion
    - docker-completion
    - pip-completion
    - vagrant-completion

- name: Install compilers
  homebrew: name={{ item }} state=latest
  loop:
    - go

- name: Install DevOps Tools
  homebrew: name={{ item }} state=latest
  loop:
    - awscli
    - amazon-ecs-cli
    - packer
    - terraform
    - xhyve
    - dockviz

- name: Install Security/Privacy Tools
  homebrew: name={{ item }} state=latest
  loop:
    - ettercap
    - httping
    - nmap
    - gpg
    - sshuttle
    - tor
    - torsocks

