---
# brew components
#
- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=no

- name: Brew taps.
  homebrew_tap: tap={{ taps }} state=present
  loop:
    - caskroom/cask # may not be needed anymore
    - homebrew/cask-drivers
    - aws/tap
  loop_control:
    loop_var: taps

- name: Install Casks
  homebrew_cask: name={{ casks }} state=present
  ignore_errors: yes
  loop:
    - caffeine
    - docker
    - firefox
    - evernote
    - iterm2
    - kitematic
    - slack
    - transmission
    - pycharm-ce
  loop_control:
    loop_var: casks

- name: Install MacBook Specific casks
  homebrew_cask: name={{ laptops }} state=present
  when: ansible_model.find("MacBook") != -1
  ignore_errors: yes
  loop:
    - istumbler
    - tuntap
    - tunnelblick
  loop_control:
    loop_var: laptops

- name: Install VM stuff
  homebrew_cask: name={{ vms }} state=present
  ignore_errors: yes
  loop:
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
  loop_control:
    loop_var: vms

- name: Install Music Stuff
  homebrew_cask: name={{ musics }} state=present
  ignore_errors: yes
  loop:
    - sonos
    - spotify
  loop_control:
    loop_var: musics

- name: Install Shell Tools
  homebrew: name={{ shells }} state=latest
  loop:
    - tmux
    - speedtest_cli
    - bash-completion
    - brew-cask-completion
    - docker-completion
    - pip-completion
    - vagrant-completion
  loop_control:
    loop_var: shells

- name: Install compilers
  homebrew: name={{ compilers }} state=latest
  loop:
    - go
  loop_control:
    loop_var: compilers

- name: Install DevOps Tools
  homebrew: name={{ devops }} state=latest
  loop:
    - awscli
    - amazon-ecs-cli
    - packer
    - terraform
    - xhyve
    - dockviz
    - docker-machine
    - docker-machine-driver-xhyve # requires chmod/SUID
    - aws/tap/aws-sam-cli
  loop_control:
    loop_var: devops

- name: Install Security/Privacy Tools
  homebrew: name={{ securitys }} state=latest
  loop:
    - ettercap
    - httping
    - nmap
    - gpg
    - sshuttle
    - tor
    - torsocks
  loop_control:
    loop_var: securitys

