---
# brew components
#
- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=no

- name: Brew taps.
  homebrew_tap: tap={{ taps }} state=present
  ignore_errors: "{{ brew_ignore_errors }}"
  loop:
    - caskroom/cask # may not be needed anymore
    - homebrew/cask-drivers
    - aws/tap
  loop_control:
    loop_var: taps
  tags:
    - brew
    - taps

- name: Install Casks
  homebrew_cask: name={{ casks }} state={{ cask_state }}
  ignore_errors: "{{ cask_ignore_errors }}"
  loop:
    - caffeine
    - docker
    - firefox
    - evernote
    - iterm2
    - kitematic
    - slack
    - transmission
    - pycharm-ce
  loop_control:
    loop_var: casks
  tags:
    - brew
    - casks

- name: Install MacBook Specific casks
  homebrew_cask: name={{ laptops }} state={{ cask_state }}
  when: ansible_model.find("MacBook") != -1
  ignore_errors: "{{ cask_ignore_errors }}"
  loop:
    - istumbler
    - tuntap
    - tunnelblick
  loop_control:
    loop_var: laptops
  tags:
    - brew
    - casks

- name: Install VM stuff
  homebrew_cask: name={{ vms }} state={{ cask_state }}
  ignore_errors: "{{ cask_ignore_errors }}"
  loop:
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
  loop_control:
    loop_var: vms
  tags:
    - brew
    - casks

- name: Install music casks
  homebrew_cask: name={{ musics }} state={{ cask_state }}
  ignore_errors: "{{ cask_ignore_errors }}"
  loop:
    - sonos
    - spotify
  loop_control:
    loop_var: musics
  tags:
    - brew
    - casks

- name: Install Shell Tools
  homebrew: name={{ shells }} state={{ brew_state }}
  ignore_errors: "{{ brew_ignore_errors }}"
  loop:
    - tmux
    - bash-completion
    - brew-cask-completion
    - docker-completion
    - pip-completion
    - vagrant-completion
    - launchctl-completion
    - docker-compose-completion
    - docker-machine-completion
    - packer-completion
  loop_control:
    loop_var: shells
  tags:
    - brew
    - shell

- name: Install compilers
  homebrew: name={{ compilers }} state={{ brew_state }}
  ignore_errors: "{{ brew_ignore_errors }}"
  loop:
    - go
  loop_control:
    loop_var: compilers
  tags:
    - brew
    - compiler

- name: Install DevOps Tools
  homebrew: name={{ devops }} state={{ brew_state }}
  ignore_errors: "{{ brew_ignore_errors }}"
  loop:
    - awscli
    - amazon-ecs-cli
    - packer
    - terraform
    - xhyve
    - dockviz
    - docker-machine
    - docker-machine-driver-xhyve # requires chmod/SUID
    - speedtest_cli
    - aws/tap/aws-sam-cli
  loop_control:
    loop_var: devops
  tags:
    - brew
    - devops

- name: Install Security/Privacy Tools
  homebrew: name={{ securitys }} state={{ brew_state }}
  ignore_errors: "{{ brew_ignore_errors }}"
  loop:
    - ettercap
    - httping
    - nmap
    - gpg
    - sshuttle
    - tor
    - torsocks
  loop_control:
    loop_var: securitys
  tags:
    - brew
    - security

