---

- name: Enable screensaver password
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: Require password after 5 seconds
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 5.0
    state: present

- name: Set 24-hour clock
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "H:mm"

- name: Set "nohidden" on ~/Library
  ansible.builtin.command: chflags nohidden ~/Library
  become: true
