---
# sets macOS defaults

- name: Disable HotPlug for ImageCapture
  osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: true
    state: present

- name: Enable screensaver password
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: Require password after 5 seconds
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 5.0
    state: present

- name: Set 24-hour clock
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "H:mm"

- name: Set "nohidden" on ~/Library
  command: chflags nohidden ~/Library
