---

# specific changes for MacOS

- name: Check if bash-completion is in place.
  shell: "test -f $(brew --prefix)/etc/bash_completion && echo 'yes'"
  register: completion

- name: Add completions to .profile
  when:
    - ansible_distribution == "MacOSX"
    - ansible_pkg_mgr == "homebrew"
    - completion
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      if [ -f $(brew --prefix)/etc/bash_completion]; then
         . $(brew --prefix)/etc/bash_completion
      fi

