---
- include_tasks: "{{ item }}.yml"
  loop:
   - defaults
   - brew

- name: Include devel-IntelliJ role
  include_role:
    name: devel
    tasks_from: intellij

- name: Include vm-Docker role
  include_role:
    name: vm
    tasks_from: docker