---
# This is a very specific role that only applies to systems on the admin VLAN
- name: Manual conf of Ethernet
  ansible.builtin.command: networksetup -setmanual Ethernet {{ netadmin_address }} {{ netadmin_netmask }} {{ netadmin_gateway }}

- name: Check if vlan0 is created
  ansible.builtin.command: networksetup -listallnetworkservices
  register: networks

- name: Create vlan0
  ansible.builtin.command: "networksetup -createvlan {{ vlan0_name }} {{ vlan0_parent }} {{ vlan0_tag }}"
  when: networks.stdout.find(vlan0_name) == -1

- name: Configure vlan0 to use DHCP
  ansible.builtin.command: networksetup -setdhcp "{{ vlan0_name }} Configuration"
  when: networks.stdout.find(vlan0_name) = -1