---
- name: Create dirs.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ dir.name }}"
    state: directory
    mode: "{{ dir.mode }}"
  loop:
    - { name: 'bin', mode: '0750' }
    - { name: 'projects', mode: '0750' }
    - { name: '.ssh', mode: '0700' }
  register: dirs
  loop_control:
    loop_var: dir

- name: Debug
  debug:
    var: dirs
    verbosity: 2
  when: debug == "true"
