---
- name: Create dirs.
  file:
    path: "{{ ansible_user_dir }}/{{ item.name }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { name: 'bin', mode: '0750' }
    - { name: 'projects', mode: '0750' }
    - { name: '.ssh', mode: '0700' }
  register: dirs

- name: Debug
  debug:
    var: dirs
    verbosity: 2
  when: debug == "true"
