---
- name: SSH RC
  ansible.builtin.copy:
    src: files/sshrc
    dest: "{{ ansible_user_dir }}/.ssh/rc"
    mode: 0700
  when: dirs

- name: BASHRC
  ansible.builtin.copy:
    src: files/bashrc
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: 0640
    force: no
  register: bashrc

- name: TIMEZONE
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export TZ={{ user_tz }}"
    state: present
  when: bashrc

- name: VIMRC
  ansible.builtin.copy:
    src: files/vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: 0640
    force: yes

- debug:
    var: "{{ bashrc }}"
  when: debug == true
