---

- name: Create $HOME/bin
  file: 
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: 0750

- name: Create $HOME/projects
  file:
    path: "{{ ansible_env.HOME }}/projects"
    state: directory
    mode: 0750

- name: Copy tmux config
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: 0640

