---

- name: Create $HOME/bin
  file: 
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: 0775

- name: Create $HOME/projects
  file:
    path: "{{ ansible_env.HOME }}/projects"
    state: directory
    mode: 0750


