---
- name: test version
  shell: tmux -V
  environment:
    PATH: "{{ ansible_user_dir }}/bin:{{ ansible_env.PATH }}"
  register: tmux_version

- debug:
    var: tmux_version
  when: debug == 'true'

- name: copy over tmux2 config file
  template:
    src: files/tmux2.conf.j2
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    mode: 0740
  register: tmux_conf_present
  when:
    - tmux_version.stdout.find('2.') != -1 or tmux_version.stdout.find('master') != -1

- debug:
    var: tmux_conf_present
  when: debug

- name: Copy over tmux1 config file
  template:
    src: files/tmux.conf.j2
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    mode: 0740
  when:
    - tmux_conf_present == -1
