---
- name: install tools
  include_role:
    name: tools
    tasks_from: "{{ item }}"
  loop:
    - mtr
    - socat
    - nmap

- name: intall utils
  include_role:
    name: utils
    tasks_from: "{{ item }}"
  loop:
    - wireshark