---
- name: Install base AWS tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - awscli
    - aws-cdk
    - amazon-ecs-cli

- name: Add AWS tap
  community.general.homebrew_tap:
    name: aws/tap
    state: present

- name: Install SAM
  community.general.homebrew:
    name: aws-sam-cli
    state: present

- name: Install warrensbox/tap
  community.general.homebrew_tap:
    name: warrensbox/tap
    state: present

- name: Install awsfind
  community.general.homebrew:
    name: awsfind
    state: present
