---
- name: Install pyenv
  community.general.homebrew:
    name: pyenv
    state: present

- name: Install pyenv-virtualenv
  community.general.homebrew:
    name: pyenv-virtualenv
    state: present
