---
- name: Ensure homebrew doesn't have terraform installed
  community.general.homebrew:
    name: terraform
    state: absent

- name: add tfswitch tap
  community.general.homebrew_tap:
    name: warrensbox/tap
    state: present

- name: Install warrensbox/tap/tfswitch
  community.general.homebrew:
    name: tfswtich
    state: present

- name: Install latest terraform w/ tfswtich
  ansible.builtin.command: /usr/local/bin/tfswitch --latest