---
- name: Installing security tools
  include_role:
    name: tools
    tasks_from: "{{ item }}"
  loop:
    - nuclei
    - nmap
    - sslscan
    - ettercap
    - tor

- name: installing security utils
  include_role:
    name: utils
    tasks_from: "{{ item }}"
  loop:
    - ghidra
    - wireshark
