---

- name: include common tools
  include_role:
    name: tools
    tasks_from: "{{ item }}"
  loop:
    - bash
    - launchctl
    - mas
    - gnupg
    - pass

- name: install common utilities
  include_role:
    name: utils
    tasks_from: "{{ item }}"
  loop:
    - authy
    - bitwarden
    - evernote
    - firefox
    - iterm
    - slack
