---
- name: Include utils
  include_role:
    name: utils
    tasks_from: "{{ item }}"
  loop:
    - amethyst

- name: allow remote access
  ansible.builtin.command:
    cmd: systemsetup -setremotelogin on
  become: yes

- name: activate sshd
  ansible.builtin.command:
    cmd: launchctl load -w /System/Library/LaunchDaemons/ssh.plist

- name: restart on power failure
  ansible.builtin.command:
    cmd: systemsetup -setrestartpowerfailure on
  become: yes
